version: "3"
services:
  web:
    image: training/webapp
    ports:
      - "5000:5000"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6739"
    volumes:
      - ./data:/data
    networks:
      - webnet
networks:
  webnet:
